# Generated by Django 3.1.4 on 2020-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_auto_20201219_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='Test Item'),
            preserve_default=False,
        ),
    ]
