# Generated by Django 3.1.4 on 2020-12-20 20:30

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0008_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=phone_field.models.PhoneField(default=0, max_length=31),
        ),
    ]
